// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: CommonIndexFileFormat.proto

package ciff

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is the CIFF header. It always comes first.
type Header struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version          int32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`                                             // Version.
	NumPostingsLists int32 `protobuf:"varint,2,opt,name=num_postings_lists,json=numPostingsLists,proto3" json:"num_postings_lists,omitempty"` // Exactly the number of PostingsList messages that follow the Header.
	NumDocs          int32 `protobuf:"varint,3,opt,name=num_docs,json=numDocs,proto3" json:"num_docs,omitempty"`                              // Exactly the number of DocRecord messages that follow the PostingsList messages.
	// The total number of postings lists in the collection; the vocabulary size. This might differ from
	// num_postings_lists, for example, because we only export the postings lists of query terms.
	TotalPostingsLists int32 `protobuf:"varint,4,opt,name=total_postings_lists,json=totalPostingsLists,proto3" json:"total_postings_lists,omitempty"`
	// The total number of documents in the collection; might differ from num_doc_records for a similar reason as above.
	TotalDocs int32 `protobuf:"varint,5,opt,name=total_docs,json=totalDocs,proto3" json:"total_docs,omitempty"`
	// The total number of terms in the entire collection. This is the sum of all document lengths of all documents in
	// the collection.
	TotalTermsInCollection int64 `protobuf:"varint,6,opt,name=total_terms_in_collection,json=totalTermsInCollection,proto3" json:"total_terms_in_collection,omitempty"`
	// The average document length. We store this value explicitly in case the exporting application wants a particular
	// level of precision.
	AverageDoclength float64 `protobuf:"fixed64,7,opt,name=average_doclength,json=averageDoclength,proto3" json:"average_doclength,omitempty"`
	// Description of this index, meant for human consumption. Describing, for example, the exporting application,
	// document processing and tokenization pipeline, etc.
	Description string `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *Header) Reset() {
	*x = Header{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CommonIndexFileFormat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_CommonIndexFileFormat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_CommonIndexFileFormat_proto_rawDescGZIP(), []int{0}
}

func (x *Header) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Header) GetNumPostingsLists() int32 {
	if x != nil {
		return x.NumPostingsLists
	}
	return 0
}

func (x *Header) GetNumDocs() int32 {
	if x != nil {
		return x.NumDocs
	}
	return 0
}

func (x *Header) GetTotalPostingsLists() int32 {
	if x != nil {
		return x.TotalPostingsLists
	}
	return 0
}

func (x *Header) GetTotalDocs() int32 {
	if x != nil {
		return x.TotalDocs
	}
	return 0
}

func (x *Header) GetTotalTermsInCollection() int64 {
	if x != nil {
		return x.TotalTermsInCollection
	}
	return 0
}

func (x *Header) GetAverageDoclength() float64 {
	if x != nil {
		return x.AverageDoclength
	}
	return 0
}

func (x *Header) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// An individual posting.
type Posting struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Docid int32 `protobuf:"varint,1,opt,name=docid,proto3" json:"docid,omitempty"` //the *delta-gap* compressed docid
	Tf    int32 `protobuf:"varint,2,opt,name=tf,proto3" json:"tf,omitempty"`       //the term frequency, or the impact score
}

func (x *Posting) Reset() {
	*x = Posting{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CommonIndexFileFormat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Posting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Posting) ProtoMessage() {}

func (x *Posting) ProtoReflect() protoreflect.Message {
	mi := &file_CommonIndexFileFormat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Posting.ProtoReflect.Descriptor instead.
func (*Posting) Descriptor() ([]byte, []int) {
	return file_CommonIndexFileFormat_proto_rawDescGZIP(), []int{1}
}

func (x *Posting) GetDocid() int32 {
	if x != nil {
		return x.Docid
	}
	return 0
}

func (x *Posting) GetTf() int32 {
	if x != nil {
		return x.Tf
	}
	return 0
}

// A postings list, comprised of one ore more postings.
type PostingsList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Term     string     `protobuf:"bytes,1,opt,name=term,proto3" json:"term,omitempty"` // The term.
	Df       int64      `protobuf:"varint,2,opt,name=df,proto3" json:"df,omitempty"`    // The document frequency.
	Cf       int64      `protobuf:"varint,3,opt,name=cf,proto3" json:"cf,omitempty"`    // The collection frequency.
	Postings []*Posting `protobuf:"bytes,4,rep,name=postings,proto3" json:"postings,omitempty"`
}

func (x *PostingsList) Reset() {
	*x = PostingsList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CommonIndexFileFormat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostingsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostingsList) ProtoMessage() {}

func (x *PostingsList) ProtoReflect() protoreflect.Message {
	mi := &file_CommonIndexFileFormat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostingsList.ProtoReflect.Descriptor instead.
func (*PostingsList) Descriptor() ([]byte, []int) {
	return file_CommonIndexFileFormat_proto_rawDescGZIP(), []int{2}
}

func (x *PostingsList) GetTerm() string {
	if x != nil {
		return x.Term
	}
	return ""
}

func (x *PostingsList) GetDf() int64 {
	if x != nil {
		return x.Df
	}
	return 0
}

func (x *PostingsList) GetCf() int64 {
	if x != nil {
		return x.Cf
	}
	return 0
}

func (x *PostingsList) GetPostings() []*Posting {
	if x != nil {
		return x.Postings
	}
	return nil
}

// A record containing metadata about an individual document.
type DocRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Docid           int32  `protobuf:"varint,1,opt,name=docid,proto3" json:"docid,omitempty"`                                           // Refers to the docid in the postings lists.
	CollectionDocid string `protobuf:"bytes,2,opt,name=collection_docid,json=collectionDocid,proto3" json:"collection_docid,omitempty"` // Refers to a docid in the external collection.
	Doclength       int32  `protobuf:"varint,3,opt,name=doclength,proto3" json:"doclength,omitempty"`                                   // Length of this document.
}

func (x *DocRecord) Reset() {
	*x = DocRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CommonIndexFileFormat_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocRecord) ProtoMessage() {}

func (x *DocRecord) ProtoReflect() protoreflect.Message {
	mi := &file_CommonIndexFileFormat_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocRecord.ProtoReflect.Descriptor instead.
func (*DocRecord) Descriptor() ([]byte, []int) {
	return file_CommonIndexFileFormat_proto_rawDescGZIP(), []int{3}
}

func (x *DocRecord) GetDocid() int32 {
	if x != nil {
		return x.Docid
	}
	return 0
}

func (x *DocRecord) GetCollectionDocid() string {
	if x != nil {
		return x.CollectionDocid
	}
	return ""
}

func (x *DocRecord) GetDoclength() int32 {
	if x != nil {
		return x.Doclength
	}
	return 0
}

var File_CommonIndexFileFormat_proto protoreflect.FileDescriptor

var file_CommonIndexFileFormat_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x46, 0x69, 0x6c,
	0x65, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63,
	0x69, 0x66, 0x66, 0x22, 0xc6, 0x02, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x12, 0x6e, 0x75, 0x6d, 0x5f,
	0x70, 0x6f, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x6e, 0x75, 0x6d, 0x50, 0x6f, 0x73, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x4c, 0x69, 0x73, 0x74, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x75, 0x6d, 0x5f, 0x64, 0x6f,
	0x63, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6e, 0x75, 0x6d, 0x44, 0x6f, 0x63,
	0x73, 0x12, 0x30, 0x0a, 0x14, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x69,
	0x6e, 0x67, 0x73, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x12, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x6f, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x4c, 0x69,
	0x73, 0x74, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x64, 0x6f, 0x63,
	0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x44, 0x6f,
	0x63, 0x73, 0x12, 0x39, 0x0a, 0x19, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x74, 0x65, 0x72, 0x6d,
	0x73, 0x5f, 0x69, 0x6e, 0x5f, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x16, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x54, 0x65, 0x72, 0x6d,
	0x73, 0x49, 0x6e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2b, 0x0a,
	0x11, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x64, 0x6f, 0x63, 0x6c, 0x65, 0x6e, 0x67,
	0x74, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x10, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67,
	0x65, 0x44, 0x6f, 0x63, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2f, 0x0a, 0x07,
	0x50, 0x6f, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x6f, 0x63, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x64, 0x6f, 0x63, 0x69, 0x64, 0x12, 0x0e, 0x0a,
	0x02, 0x74, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x74, 0x66, 0x22, 0x6d, 0x0a,
	0x0c, 0x50, 0x6f, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x65, 0x72, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x72,
	0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x64, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x64,
	0x66, 0x12, 0x0e, 0x0a, 0x02, 0x63, 0x66, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x63,
	0x66, 0x12, 0x29, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x69, 0x66, 0x66, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x69,
	0x6e, 0x67, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x6a, 0x0a, 0x09,
	0x44, 0x6f, 0x63, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x6f, 0x63,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x64, 0x6f, 0x63, 0x69, 0x64, 0x12,
	0x29, 0x0a, 0x10, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x64, 0x6f,
	0x63, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x6f, 0x63, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x6f,
	0x63, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x64,
	0x6f, 0x63, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x42, 0x07, 0x5a, 0x05, 0x2f, 0x63, 0x69, 0x66,
	0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_CommonIndexFileFormat_proto_rawDescOnce sync.Once
	file_CommonIndexFileFormat_proto_rawDescData = file_CommonIndexFileFormat_proto_rawDesc
)

func file_CommonIndexFileFormat_proto_rawDescGZIP() []byte {
	file_CommonIndexFileFormat_proto_rawDescOnce.Do(func() {
		file_CommonIndexFileFormat_proto_rawDescData = protoimpl.X.CompressGZIP(file_CommonIndexFileFormat_proto_rawDescData)
	})
	return file_CommonIndexFileFormat_proto_rawDescData
}

var file_CommonIndexFileFormat_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_CommonIndexFileFormat_proto_goTypes = []any{
	(*Header)(nil),       // 0: ciff.Header
	(*Posting)(nil),      // 1: ciff.Posting
	(*PostingsList)(nil), // 2: ciff.PostingsList
	(*DocRecord)(nil),    // 3: ciff.DocRecord
}
var file_CommonIndexFileFormat_proto_depIdxs = []int32{
	1, // 0: ciff.PostingsList.postings:type_name -> ciff.Posting
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_CommonIndexFileFormat_proto_init() }
func file_CommonIndexFileFormat_proto_init() {
	if File_CommonIndexFileFormat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_CommonIndexFileFormat_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Header); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CommonIndexFileFormat_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Posting); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CommonIndexFileFormat_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*PostingsList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CommonIndexFileFormat_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*DocRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_CommonIndexFileFormat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CommonIndexFileFormat_proto_goTypes,
		DependencyIndexes: file_CommonIndexFileFormat_proto_depIdxs,
		MessageInfos:      file_CommonIndexFileFormat_proto_msgTypes,
	}.Build()
	File_CommonIndexFileFormat_proto = out.File
	file_CommonIndexFileFormat_proto_rawDesc = nil
	file_CommonIndexFileFormat_proto_goTypes = nil
	file_CommonIndexFileFormat_proto_depIdxs = nil
}
